DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS books;

CREATE TABLE author(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
author_id INT NOT NULL REFERENCES author (id),
title VARCHAR(250) NOT NULL,
price_old VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);